name: Push Checks

on:
  pull_request: {}
jobs:
  builds:
    name: Builds
    uses: ./.github/workflows/build.yml
    secrets:
      unityLicense: ${{ secrets.UNITY_LICENSE }}
      githubToken: ${{ secrets.GITHUB_TOKEN }}
